name: mobileapp
description: The XemoTransfer mobile application.

# Prevent accidental publishing to pub.dev.
#https://github.com/projectpipeline/app_pipeline_sdk.git
publish_to: 'none'

version: 0.3.3+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_amplifysdk:
    git:
      url: git@github.com:projectpipeline/app_pipeline_sdk.git
      ref: feature/xemo-use-api
      version: "4.1.3"
  jiffy: ^5.0.0
  package_info_plus: ^1.4.2
  device_info_plus: ^3.2.3
  flutter_native_splash: ^2.1.6
  amplify_flutter: ^0.6.8
  amplify_auth_cognito: ^0.6.8
  amplify_analytics_pinpoint: ^0.6.8
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.15
  amplify_datastore: ^0.6.8
  amplify_api: ^0.6.8
  amplify_storage_s3: ^0.6.8
  carousel_slider:
  font_awesome_flutter: ^10.1.0
  expandable:
  flutter_svg: ^1.0.3
  flutter_spinkit:
  animated_splash_screen:
  uuid:
  http:
  get: ^4.6.5
  avatar_glow: ^2.0.2
  form_field_validator:
  flutter_screenutil:
  path_provider:
  statemachine:
  flutter_dotenv:
  intl:
  test:
  card_swiper: ^2.0.1
  connectivity_plus: ^2.2.1
  badges: ^2.0.2
  platform: ^3.1.0
# flutter_widget_from_html: ^0.8.5
  screen_size_test: ^1.0.2+3
  libphonenumber_plugin: ^0.2.3
  equatable: ^2.0.0
  collection: ^1.15.0
  firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.5.2
  aws_pinpoint_api: ^1.2.0
  grouped_list: ^5.1.2
  flutter_contacts: ^1.1.5
  firebase_analytics: ^9.3.4
  store_redirect: ^2.0.1
  mailer: ^5.1.1
  permission_handler: ^10.0.1
  webview_flutter: ^3.0.4
  alphanum_comparator: ^2.0.1
  local_session_timeout: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.1"
# flutter_native_splash:
#   color: "#66DAC0"
#   image: "assets/splash.png"
#   android_gravity: center
#   ios_content_mode: center
#   android: true
#   ios: true
#   web: false
#   fullscreen: true
flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: "launcher_icon"
  ios: true
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/flags/
    - assets/splash.png
    - assets/images/caroussel/
    - assets/flutter_i18n/en.json
    - assets/flutter_i18n/fr.json
    - assets/icons/
    - assets/xemo/
    - assets/dev.env
    - assets/wks.env
    - assets/prod.env
    - assets/xemo_flags/
  fonts:
     - family: Ubuntu
       fonts:
         - asset: fonts/Ubuntu-Light.ttf
           weight: 300
         - asset: fonts/Ubuntu-LightItalic.ttf
           weight: 300
           style: italic
         - asset: fonts/Ubuntu-Regular.ttf
           weight: 400
         - asset: fonts/Ubuntu-Medium.ttf
           weight: 500
         - asset: fonts/Ubuntu-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: fonts/Ubuntu-Bold.ttf
           weight: 700
         - asset: fonts/Ubuntu-BoldItalic.ttf
           weight: 700
           style: italic
